// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumR7R303dl4Jym9RUemph7kta7llY4Eg',
    appId: '1:568807803174:android:9893c8d37631eac45cd9e7',
    messagingSenderId: '568807803174',
    projectId: 'sayno-6bbdd',
    storageBucket: 'sayno-6bbdd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANQNvxHtm9-4w7x3iYb3r52HnYh7hm6Ik',
    appId: '1:568807803174:ios:42e142c93eac00af5cd9e7',
    messagingSenderId: '568807803174',
    projectId: 'sayno-6bbdd',
    storageBucket: 'sayno-6bbdd.firebasestorage.app',
    iosBundleId: 'com.example.sayno',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_nCljG3g0vhxCI6R7Rszwrsv1yd2bvns',
    appId: '1:568807803174:web:70b28e21a02e5c755cd9e7',
    messagingSenderId: '568807803174',
    projectId: 'sayno-6bbdd',
    authDomain: 'sayno-6bbdd.firebaseapp.com',
    storageBucket: 'sayno-6bbdd.firebasestorage.app',
    measurementId: 'G-N70L87Q6TG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANQNvxHtm9-4w7x3iYb3r52HnYh7hm6Ik',
    appId: '1:568807803174:ios:42e142c93eac00af5cd9e7',
    messagingSenderId: '568807803174',
    projectId: 'sayno-6bbdd',
    storageBucket: 'sayno-6bbdd.firebasestorage.app',
    iosBundleId: 'com.example.sayno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_nCljG3g0vhxCI6R7Rszwrsv1yd2bvns',
    appId: '1:568807803174:web:e862d966151ba5475cd9e7',
    messagingSenderId: '568807803174',
    projectId: 'sayno-6bbdd',
    authDomain: 'sayno-6bbdd.firebaseapp.com',
    storageBucket: 'sayno-6bbdd.firebasestorage.app',
    measurementId: 'G-PHHZY1BMV8',
  );
}
